### ISSUE TITLE
Verbose messaging and terminal trace back info

### ISSUE THREAD

**Issue by CraigAD** [xybu/onedrive-d-old#92] opened 2014-11-25 03:30 UTC
I have just started using onedrive-d and completed my Ubuntu 10GB backup a couple of days ago.  Since then, I have onedrive-d startup during the boot.  It  appears to be working and I can identify with some of the issues listed by others.  I thought that after the first two days that the backup sync to OneDrive had completed, but each day there is a lot of network traffic 500kB or more that will go for hours including the messaging -- and I have not changed anything.  I look at my terminal to see what state the backup is in and there is no information that I can decifer.  I use Unison with Box.com where a similar manual sync process is involved, but in this case, Unison provides a short and succinct message that is easy to interpret.  I understand that the development of onedrive-d is in its earliest stages, but I just wanted to suggest how important clear messaging is to the end user -- I don't know when it has started, what state it is in, or if any errors have occured, or when it has completed.  A log is a better place for more verbose reports -- but always I must be able to figure out what it all means, in case there is an error caused by something that I did.  Thanks for the great work that you have done to provide onedrive-d.

**Comment by xybu** [comment] 2014-11-25 03:36
For an in-development program, what is more important is to know what the program has been doing in case any bug happens. This makes it easier to analyze the causes of problems when one shares the log with me. I am aware that currently there are more than necessary print statements. When the app is mature enough the log level will be raised and there will be much less log content.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by CraigAD** [comment] 2014-11-25 17:26
I agree with you in principle, my only point is that the feedback should let the user know whether it is working properly or not.

Here is a listing of the first few files in the local directory that is sync'd with OneDrive.  Each of the files is about 52.5MB, except those labelled as "manifest."  Since each file is duplicated, the folder has grown very large.  The files were placed into the sync folder once and have not been touched since.

/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.manifest.gpg
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.manifest.gpg (OLDER_1416705285.78)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.manifest.gpg (OLDER_1416705285.78) (OLDER_1416705285.78)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.manifest.gpg (OLDER_1416705285.78) (OLDER_1416705285.78) (OLDER_1416705285.78)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol1.difftar.gpg
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol1.difftar.gpg (OLDER_1416704733.0)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol1.difftar.gpg (OLDER_1416704733.0) (OLDER_1416704733.0)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol1.difftar.gpg (OLDER_1416704733.0) (OLDER_1416704733.0) (OLDER_1416704733.0)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol2.difftar.gpg
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol2.difftar.gpg (OLDER_1416704738.17)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol2.difftar.gpg (OLDER_1416704738.17) (OLDER_1416704738.17) (OLDER_1416704738.17)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol3.difftar.gpg
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol3.difftar.gpg (OLDER_1416704743.06)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol3.difftar.gpg (OLDER_1416704743.06) (OLDER_1416704743.06) (OLDER_1416704743.06)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol4.difftar.gpg
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol4.difftar.gpg (OLDER_1416704747.43)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol4.difftar.gpg (OLDER_1416704747.43) (OLDER_1416704747.43) (OLDER_1416704747.43)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol5.difftar.gpg
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol5.difftar.gpg (OLDER_1416704753.01)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol5.difftar.gpg (OLDER_1416704753.01) (OLDER_1416704753.01)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol5.difftar.gpg (OLDER_1416704753.01) (OLDER_1416704753.01) (OLDER_1416704753.01)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol6.difftar.gpg
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol6.difftar.gpg (OLDER_1416704758.59)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol6.difftar.gpg (OLDER_1416704758.59) (OLDER_1416704758.59) (OLDER_1416704758.59)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol7.difftar.gpg
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol7.difftar.gpg (OLDER_1416704762.71)
/home/cad/OneDrive/Documents/deja-dup/duplicity-full.20141123T010523Z.vol7.difftar.gpg (OLDER_1416704762.71) (OLDER_1416704762.71) (OLDER_1416704762.71)

**Comment by xybu** [comment] 2015-02-23 09:50
The "NEWER" "OLDER" issue was addressed in 1.0-dev thanks to SQLite database.
The stuff in `future` branch standardized the log so you can turn off the debug log entries. You might try it out if you don't need GUI.
Large files will be processed in smaller chunks when uploading / downloading.

**Closed as completed by xybu** 2015-02-23 09:50 UTC
