### ISSUE TITLE
Adds "NEWER_xxx" or "OLDER_xxx" at the end of all files

### ISSUE THREAD

**Issue by leolivier** [xybu/onedrive-d-old#64] opened 2014-09-06 14:46 UTC
Hi,
I'm a onedrive-d user since yesterday, thanks for this, I've been waiting for it for a long time!
But I got two big issues when using it on my Linux Mint 17 (Quiara).
First of all, almost all of my files have been renamed with either someting like "(NEWER_xxx)" or '(OLDER_xxx)" at the end...
For instance: "20130922_152148_Android.jpg (NEWER_1393719369.0)"
or "20130531_091154_Android.jpg (OLDER_1393706583.0)"
As you can imagine, it's no longer possible to open easlily a file named 20130531_091154_Android.jpg (OLDER_1393706583.0) based on its suffix which is now in the middle... :-/

Some times, the original files still exists (the one without the suffix) but most of the times not. For instance:
/data/OneDrive/Images/Pellicule/20130806_151840_Android.jpg
/data/OneDrive/Images/Pellicule/20130806_151840_Android.jpg (OLDER_1396738997.0)
And they are both 143.4kB large and updated on 06-04-2014
I even found things like:
/data/OneDrive/Photos/2004/DSCN1424.JPG
/data/OneDrive/Photos/2004/DSCN1424.JPG (NEWER_1336234185.0) (OLDER_1336234185.0)

The other issue is an exception (and seems to be linked to the previous issue). Here is the trace:

Traceback (most recent call last): 

  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 478, in resolve_path
    self.listdir(root_id)))[name]
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 497, in listdir
    offset=offset)['data']
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 346, in listdir
    return self(ujoin(folder_id, 'files'), dict(limit=limit, offset=offset))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 329, in **call**
    return self.request(api_url(), **kwz).

  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 176, in request
    raise raise_for.get(code, ProtocolError)(code, message)
onedrive.api_v5.ProtocolError: (None, MaxRetryError("HTTPSConnectionPool(host='apis.live.net', port=443): Max retries exceeded with url: /v5.0/folder.31100c4dd70e082d.31100C4DD70E082D!8221/files?access_token=... (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)",))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/data/OneDrive/Images/Pellicule/20130922_152434_Android.jpg'

The last sentence in french means: no such file or directory...
This file 20130922_152434_Android.jpg indeed doe not exist on my Linux but another one named "20130922_152434_Android.jpg (NEWER_1393719155.0)" exists

Thnaks for your attention and hopefully for a solution to my first issue which creates a big mess...

**Comment by leolivier** [comment] 2014-09-06 17:27
Hi again,
I think I found the problem.
I started synchronizing with onedrive-d in a directory that was not empty.
This directory already contained an older synchronisation built using storage made easy.
I restarted a bran new sync into an empty directory and everything seems to work fine up to now.
If something goes wrong again (especially with the second issue) I'll reopen the case

**Comment by leolivier** [comment] 2014-09-07 11:01
Hi, 
me again.
I still have the second issue but on another file, see below. This file exist on OneDrive, I can browse it through the onedrive.com site.

Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 478, in resolve_path
    self.listdir(root_id)))[name]
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 497, in listdir
    offset=offset)['data']
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 346, in listdir
    return self(ujoin(folder_id, 'files'), dict(limit=limit, offset=offset))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 329, in **call**
    return self.request(api_url(), **kwz)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 176, in request
    raise raise_for.get(code, ProtocolError)(code, message)
onedrive.api_v5.ProtocolError: (None, MaxRetryError("HTTPSConnectionPool(host='apis.live.net', port=443): Max retries exceeded with url: /v5.0/folder.31100c4dd70e082d.31100C4DD70E082D!8221/files?access_token=... (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)",))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/data/OneDrive/Images/Pellicule/20120629_170508_Android_2014-04-05_18-13-56.jpg'

I stopped the daemon and started it again and now it complains on another file /data/OneDrive/Photos/2005/DSCN2170.JPG which also exists... Then it seems to hang (the last file updated is /data/OneDrive/Photos/2005/DSCN2169.JPG)

I also noticed things like:
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==14.08.0', 'console_scripts', 'onedrive-cli')()
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 310, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 239, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or resolve_path_wrap(s)) \
  File "/usr/local/lib/python2.7/dist-packages/onedrive/cli_tool.py", line 238, in <lambda>
    resolve_path_wrap = lambda s: api.resolve_path(s and s.replace('\', '/').strip('/'))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 478, in resolve_path
    self.listdir(root_id)))[name]
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 497, in listdir
    offset=offset)['data']
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 346, in listdir
    return self(ujoin(folder_id, 'files'), dict(limit=limit, offset=offset))
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 329, in **call**
    return self.request(api_url(), **kwz)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/api_v5.py", line 176, in request
    raise raise_for.get(code, ProtocolError)(code, message)
onedrive.api_v5.ProtocolError: (500, {u'message': u'An unexpected processing error occurred. Please contact Microsoft.', u'code': u'server_internal_error'})
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 123, in run
    self.consume(task)
  File "/usr/local/lib/python2.7/dist-packages/onedrive_d-0.85-py2.7.egg/onedrive_d/components.py", line 87, in consume
    old_mtime = os.stat(t.p1).st_mtime
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/data/OneDrive/Photos/2005/DSCN2217.JPG'

which states an internal server error on microsoft's server.
Neither file exist on local side...
Any idea on what goes wrong?

**Comment by xybu** [comment] 2014-09-07 15:17
OneDrive API has certain undocumented limit how many files you can fetch in a given period of time. 
                      =

**Comment by Dutchglory** [comment] 2014-09-07 15:22
I've tried today again, (on Ubuntu Trusty x64) now it only downloads folders, no files ... 
but still like it :) hope you can make it work ....

**Comment by xybu** [comment] 2014-09-07 15:25
Folders are actually mkdir-ed by the synchronizer, not downloaded. Only files are uploaded / downloaded.

Could you try `onedrive-cli get SOME_FILE > SOME_FILE` (if I remember correctly…) to see if you can download a file manually?

**Comment by leolivier** [comment] 2014-09-07 17:03
On my side, I had to chnage the number of worker to 4 as, when an exception occurs, the worker dies and I have to kill the daemon and rerun it so that it resumes downloading...
Maybe you could change the way it works so that workers don't die when an exception occurs?
By the way, it doesn't seem to be related to the number of downloads. When I restart the daemon, new download take place until exceptions occur (sometimes hundreds of dowloads later)

**Comment by sanchomuzax** [comment] 2014-09-10 20:27
Similar problem with a lot of NEWER_xxx and OLDER_xxx files. I stoped the service while repair the bug.

**Comment by xybu** [comment] 2014-09-10 22:59
There is no workaround for this issue given the architecture of version 0.85. You can't decide which file in a conflicting pair is strictly newer merely by comparing the mtime. Otherwise you'll lose data.

Version 1.0-dev introduces a sqlite database which can reduce greatly the occurrence of this type of conflicts. But it is still far from alpha stage.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by PtBu3** [comment] 2014-10-09 05:09
Same issue on Ubuntu 14.04 with a lot of NEWER_xxx and OLDER_xxx files making working with the respective directories virtually impossible after several syncs. I would be very happy if version 1.0 solves this problem.

**Comment by xybu** [comment] 2014-10-24 06:54
Could you check if 1.0 solves (precisely, mitigates) the problem?

**Comment by leolivier** [comment] 2014-10-24 14:29
Le 24/10/2014 08:54, Xiangyu Bu a écrit :

> Could you check if 1.0 solves (precisely, mitigates) the problem?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xybu/onedrive-d/issues/64#issuecomment-60350950.
> 
> Hi,
> I installed the latest version and rerun the scripts.
> At the moment, I got an exception at start:

Exception in thread worker-0:
Traceback (most recent call last):
   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
     self.run()
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 418, in run
     local_path = row['local_path'])
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/live_api.py", 
line 284, in put
     else: raise ProtocolError(ret)
live_api.ProtocolError: "resource_already_exists: The resource couldn't 
be created because a resource named 'Ordinateur portable de Olivier' 
already exists."

then a few minutes later, I get another exception:

Exception in thread worker-1:
Traceback (most recent call last):
   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
     self.run()
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 405, in run
     self.do_postwork(row)
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 364, in do_postwork
     self.update_entry(new_info)
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 305, in update_entry
     update_entry(self.conn, entry)
   File 
"/home/olivier/Téléchargements/onedrive-d-1.0-dev/onedrive_d/daemon.py", 
line 109, in update_entry
     '(:parent_path, :name, :id, :parent_id, :type, :size, 
:client_updated_time, :status)', entry)
sqlite3.OperationalError: database is locked

which kills the 2 workers as far as I understand...

**Comment by xybu** [comment] 2014-10-24 15:34
Is the local repo originally empty? Is the entry mentioned in the log a file or folder?

At first glance it reads like the program finds a local entry that does not exist remotely and then tries to upload it but is told that the entry already exists. I don't have idea how this happens. If the issue can be reproduced, could you send me some program log that relates to the entry?

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by leolivier** [comment] 2014-10-24 15:57
No, the local repo is not empty, I restarted from the last test with the 
previous version (I have around 20GB to download so it's hard to start 
fresh each time :)
The first metioned entry is a onenote file. It's ~5kB on the ondrive 
server but 0B on my local directory. It seems that the failure is when 
uploading so uploading a 0B file might not work maybe?

For the second exception, the exception occurs when downloading a photo...

I attached the log file to this mail...

**Comment by xybu** [comment] 2014-10-24 15:58
That makes sense. OneNote links are disasters to handle given the OneDrive API... But I'll try.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by ahogen** [comment] 2015-02-01 08:32
A little bit behind on this issue, but I wanted to add that I too found that a bunch of my files (not all) were renamed to "new/old", even when they weren't changed. I imagine it's because I had onedrive-d start out with a repo that had files (all of them) that where previously synced by the Windows 7 OneDrive application.

Hope that helps, somehow.

**Comment by noahdsmith** [comment] 2015-02-04 11:55
I have also had this problem, with files being recursively duplicated with OLDER_... appended. This is with the latest version.

**Comment by xybu** [comment] 2015-02-23 10:01
I deleted `master` branch so 0.8.x won't get distributed anymore.

As a revisit of this post, it looks like all problems mentioned have been addressed in `future` branch (ver 1.1? TBD.) Smoother data transfer, conflict resolving, database lock, etc.

**Closed as completed by xybu** 2015-02-23 10:01 UTC
Labels: duplicate, solved
